/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-strong': 'var(--color-primary-strong)',
        secondary: 'var(--color-secondary)',
        muted: 'var(--color-muted)',
        accent: 'var(--color-accent)',
        'accent-bright': 'var(--color-accent-bright)',
        'accent-pressed': 'var(--color-accent-pressed)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-low': 'var(--color-surface-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-high': 'var(--color-surface-high)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        success: 'var(--color-success)',
        error: 'var(--color-error)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
        'dot-laozi': 'var(--color-dot-laozi)',
        'dot-zhuangzi': 'var(--color-dot-zhuangzi)',
        'dot-lushi-chunqiu': 'var(--color-dot-lushi-chunqiu)',
        'dot-wenzi': 'var(--color-dot-wenzi)',
        'dot-guanzi': 'var(--color-dot-guanzi)',
        'dot-hanfeizi': 'var(--color-dot-hanfeizi)',
        'dot-shanhaijing': 'var(--color-dot-shanhaijing)',
        'dot-shiji': 'var(--color-dot-shiji)',
        'highlight-laozi': 'var(--color-highlight-laozi)',
        'highlight-zhuangzi': 'var(--color-highlight-zhuangzi)',
        'highlight-lushi-chunqiu': 'var(--color-highlight-lushi-chunqiu)',
        'highlight-wenzi': 'var(--color-highlight-wenzi)',
        'highlight-guanzi': 'var(--color-highlight-guanzi)',
        'highlight-hanfeizi': 'var(--color-highlight-hanfeizi)',
        'highlight-shanhaijing': 'var(--color-highlight-shanhaijing)',
        'highlight-shiji': 'var(--color-highlight-shiji)',
      },
      borderRadius: {
        'token-sm': 'var(--radius-sm)',
        'token-button': 'var(--radius-button)',
        'token-popover': 'var(--radius-popover)',
        'token-modal': 'var(--radius-modal)',
        'token-lg': 'var(--radius-lg)',
        'token-toggle': 'var(--radius-toggle)',
      },
      boxShadow: {
        popover: 'var(--shadow-popover)',
        modal: 'var(--shadow-modal)',
        panel: 'var(--shadow-panel)',
      },
      width: {
        sidebar: 'var(--sidebar-width)',
        'reading-column': 'var(--main-text-max-width)',
      },
      maxWidth: {
        'reading-column': 'var(--main-text-max-width)',
      },
      height: {
        topbar: 'var(--top-bar-height)',
      },
      fontFamily: {
        zh: ['"Noto Serif SC"', 'serif'],
        serif: ['"Noto Serif SC"', 'serif'],
        sans: ['Inter', '-apple-system', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'heading-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'zh-body': ['var(--zh-body-size)', { lineHeight: 'var(--zh-body-line-height)' }],
        'en-body': ['var(--en-body-size)', { lineHeight: 'var(--en-body-line-height)' }],
        'ui-label': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'ui-small': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        eyebrow: ['14px', { lineHeight: '20px', letterSpacing: '0.2em', fontWeight: '500' }],
      },
      transitionDuration: {
        panel: '300ms',
        popover: '150ms',
        modal: '200ms',
      },
    },
  },
  plugins: [],
};
